### ISSUE TITLE
Problem with coffeescript adder

### ISSUE THREAD

**Issue by johndeighan** [babichjacob/finite#1]
Sorry, dude, but I couldn't find how to add an issue to your coffeescript svelte adder project.

The page says to use `<script lang="coffee">` to enter CoffeeScript. However, that didn't work for me at all. On a lark, I tried changing it to `<script type="coffee">` and, magically, it started working. You might want to check that README.

**Comment by babichjacob** [comment]
Moved issue to the `svelte-add` repository: https://github.com/svelte-add/svelte-add/issues/188
